name: lucid_org
description: "Organizational efficiency platform"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 2.1.4

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  provider: ^6.1.2
  firebase_core: ^3.6.0
  cloud_firestore: ^5.4.4
  logging: ^1.3.0

  flutter_rating_bar:
    git:
      url: https://github.com/Michkwetzel/flutter_rating_bar_custom.git
      ref: main  # Use the branch
  universal_html: ^2.2.4
  http: ^1.3.0
  jwt_decoder: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: Nunito
      fonts:
        - asset: fonts/nunito/Nunito-VariableFont_wght.ttf
    - family: Noto Sans
      fonts:
        - asset: fonts/noto_sans/NotoSans-VariableFont_wdth,wght.ttf


  assets:
    - assets/logo/
